codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "80...100"

  status:
    project:
      default: off
      frontend:
        flags: frontend
        base: parent
      backend:
        flags: backend
        base: parent
    patch:
      default: off
      frontend:
        flags: frontend
        base: parent
      backend:
        flags: backend
        base: parent

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: no
